version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_web
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=product_db
      - DB_USER=root
      - DB_PASS=root
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  postgres_data:
